<?php

namespace AppBundle\Repository;

/**
 * DocumentDriverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentDriverRepository extends \Doctrine\ORM\EntityRepository{
  
}