<?php

namespace AppBundle\Repository;

/**
 * PhotoAdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoAdRepository extends \Doctrine\ORM\EntityRepository{
  
}