<?php

namespace AppBundle\Repository;

/**
 * WhereISpendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WhereISpendRepository extends \Doctrine\ORM\EntityRepository{
  
}